//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritersInn1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class getAllContent
    {
        public int WID { get; set; }
        public string WName { get; set; }
        public string WPhoto { get; set; }
        public string WBio { get; set; }
        public int CID { get; set; }
        public string CName { get; set; }
        public string CSDesc { get; set; }
        public string CLDesc { get; set; }
        public Nullable<decimal> CPrice { get; set; }
        public Nullable<int> CQuantity { get; set; }
        public string Cimage { get; set; }
    }
}
