//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritersInn1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER
    {
        public int Order_Id { get; set; }
        public int Content_Id { get; set; }
        public int Customer_Id { get; set; }
        public int Quantity { get; set; }
        public int Total_Cost { get; set; }
        public string Order_Status { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
        public virtual Tbl_Content Tbl_Content { get; set; }
    }
}
