//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritersInn1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAYMENT
    {
        public int PaymentId { get; set; }
        public decimal Amount { get; set; }
        public int Trx_id { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<bool> PaymentStatus { get; set; }
    }
}
