//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritersInn1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class REVIEW
    {
        public int ReviewId { get; set; }
        public string Review_des { get; set; }
        public Nullable<int> WriterId { get; set; }
    
        public virtual WRITER WRITER { get; set; }
    }
}
