//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WritersInn1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WRITER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WRITER()
        {
            this.REVIEWs = new HashSet<REVIEW>();
            this.Tbl_Content = new HashSet<Tbl_Content>();
        }
    
        public int WriterId { get; set; }
        public string WriterName { get; set; }
        public string WriterEmail { get; set; }
        public string WriterPass { get; set; }
        public string WriterPhone { get; set; }
        public string WriterPhoto { get; set; }
        public string WriterBio { get; set; }
        public string WriterRank { get; set; }
        public Nullable<bool> ActiveStatus { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REVIEW> REVIEWs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Content> Tbl_Content { get; set; }
    }
}
